First review.
SigmaSam/Bubble-Sort-By pull request #1
Opened 2020-07-06 15:41 UTC by SigmaSam

We recreated the bubble sorting algorithm with Ruby and adds as required, a version that uses the yield method to summon a block of code in the function as an argument.

2020-07-06 23:24 UTC, mikenath223 requested changes
### Hi Team 👋

You've both obviously worked hard on this. 👍

- [x] - However you are expected to build the bubble_sort method, kindly include the bubble_sort method.

- [x] In addition, the bubble_sort_by method doesn't return the right result, kindly fix this and test to ensure it returns the right result.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-07-06 23:42 UTC, marcoshdezcam commented
> ### Hi Team wave
> 
> You've both obviously worked hard on this. +1
> 
>     * [ ]  - However you are expected to build the bubble_sort method, kindly include the bubble_sort method.
> 
>     * [ ]  In addition, the bubble_sort_by method doesn't return the right result, kindly fix this and test to ensure it returns the right result.
> 
> 
> Kindly fix these issues and request another review+1
> Feel free to contact me on slack(michgolden) if you need further clarification.
> 
> HAPPY CODINGman_technologist

Issues solved! Thank you!

2020-07-07 11:48 UTC, mikenath223 requested changes
### Hi again Team 👋

Kindly check [this link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421588/) to see the project requirements please take note of the section Microverse Adjustments.
You are expected to build two(2) methods. The bubble_sort and the bubble_sort_by method.

I apologize if I wasn't clear in the first review.

- [ ] Also the nature of the bubble_sort method is that it sorts an array in the default ascending order if no block is passed to it, but in yours, if no block is passed it throws an error.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(mike) if you need further clarification.

HAPPY CODING👨‍💻

2020-07-07 18:29 UTC, marcoshdezcam commented
> ### Hi again Team wave
> 
> Kindly check [this link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421588/) to see the project requirements please take note of the section Microverse Adjustments.
> You are expected to build two(2) methods. The bubble_sort and the bubble_sort_by method.
> 
> I apologize if I wasn't clear in the first review.
> 
>     * [ ]  Also the nature of the bubble_sort method is that it sorts an array in the default ascending order if no block is passed to it, but in yours, if no block is passed it throws an error.
> 
> 
> Kindly fix these issues and request another review+1
> Feel free to contact me on slack(mike) if you need further clarification.
> 
> HAPPY CODINGman_technologist

Solved!

2020-07-07 20:43 UTC, mosesogwo requested changes
**Hello! :wave:, you're doing well. Just a little fix and you'll be fit to :rocket:**
- You should return sorted array values and not print them.
- Your bubble_sort_by doesn't return the correct result yet. See my comments on your code.


_**Kindly make those changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-07-07 20:43 UTC, mosesogwo commented on bubble_sort.rb
> +    print numbers
Return numbers, do not print

2020-07-07 20:43 UTC, mosesogwo commented on bubble_sort.rb
> +        end
You should check if the comparator is greater than zero, before proceeding to swap.
What you have currently will proceed to swap every time except when comparator value is false or nil.

2020-07-07 22:43 UTC, Dandush03 commented
# Status: Project Approved 

## Good luck in your next assignment

2020-07-07 22:47 UTC, merged